### PR TITLE
[#785] Add defensive coding to helpers

### LINKED ISSUE #785: [Overview] UI crashes if an approved request has no tasks
https://bugzilla.redhat.com/show_bug.cgi?id=1648460

### PR DESCRIPTION
**Pull request by michaelkro**
Fixes #785 
https://bugzilla.redhat.com/show_bug.cgi?id=1648460

In the edge case where a request that we expect to have tasks has none,
using map on vm_ids will result with [undefined] being pushed into
vmTasksForRequestOfPlan instead of an empty array.

# Notes
* To reproduce the bug as described in the BZ, delete all `ServiceTemplateTransformationPlanTask` in the rails console, but leave all existing plans and requests
* Viewing plans on Overview and in the Plan details pages should work as expected

### CODE REVIEW

File: app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js [hunk 1]
```diff
@@ -12,7 +12,13 @@ const getMostRecentVMTasksFromRequests = (requests, actions) => {
...
   vmTasksForRequestOfPlan.push(
-    vm_ids.map(vmId => commonUtilitiesHelper.getMostRecentEntityByCreationDate(groupedByVMId[vmId]))
+    vm_ids.reduce((tasks, id) => {
+      const task = commonUtilitiesHelper.getMostRecentEntityByCreationDate(groupedByVMId[id]);
+      if (task) {
+        return [...tasks, task];
+      }
+      return tasks;
+    }, [])
   );
```
Comment (AparnaKarve) [inline app/javascript/react/screens/App/Overview/components/Migrations/helpers/getMostRecentVMTasksFromRequests.js]: How about we start defending a little earlier than here?

After line#6, if we add a guard on `allTasks` like this -

```js
if (allTasks.some(task => task.id)) {
 ...
 ...
 // existing code
} else {
  return [];
}
```

I think that will be the only place we will have to worry about.

**Comment by mturley** [comment]
I'm merging this to prevent errors in tomorrow's demo, @AparnaKarve if you think we should continue the discussion and follow up with another PR let us know :)

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 62dd3e253979ddeb234ce901d7c074fa39af5de1
Author: Mike Turley <mike.turley@alum.cs.umass.edu>
Date:   Mon Nov 19 16:31:37 2018 -0500

    Merge pull request #787 from michaelkro/785-guard-against-no-tasks
    
    [#785] Add defensive coding to helpers
    
    (cherry picked from commit f85e64d9b6d4159aaad1a24788b2ec43dd654929)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1648460
```
