### PR TITLE
[#653] Fixes misalignment issues in the Plan detail list when download log is in progress

### LINKED ISSUE #653: Download Log causes list view misalignment
When the user selects a log to download a message is displayed saying that the log file is being downloaded. For some reason this is causing the other fields in the row to shift to the left and be mis-aligned with the other rows in the list view. The message is unnecessary. Remove it and disable the button while the file is being downloaded.

### PR DESCRIPTION
**Pull request by AparnaKarve**
Fixes #653

The Download log button or the Migration log/Pre-migration log/Post-migration log menu items would be disabled when the download log is in progress, as shown below -

screen shot 2018-09-26 at 12 24 36 pm

@michaelkro @mturley ~The second commit is for a bug that I came across while working on this issue.
I noticed that for every little component update in the Plan Detail page, the notification toasts for the tasks were being emitted. 
With the fix made in d1e6fbf, the notification toasts would be emitted only when there are `planRequestTasks` changes -- something that you would see when a migration is in progress and there are Task status updates as a result of polling.~ ---> I will be taking a look at this issue in a separate PR

### CODE REVIEW

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js [hunk 1]
```diff
@@ -68,14 +68,16 @@ class PlanRequestDetailList extends React.Component {
...
-    const {
-      failedMigrations,
-      successfulMigrations,
-      notificationsSentList,
-      dispatchVMTasksCompletionNotificationAction
-    } = this.props;
-    dispatchVMTasksCompletionNotificationAction(failedMigrations, successfulMigrations, notificationsSentList);
+  componentDidUpdate(prevProps, prevState) {
+    if (prevProps.planRequestTasks !== this.props.planRequestTasks) {
+      const {
```
Comment (michaelkro) [inline app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: Unfortunately, it seems that this conditional is still firing every time `componentDidUpdate` gets called (I confirmed this by placing a breakpoint on line 79 and waiting for the next poll).  The reason is that `planRequestTasks` is a `seamless-immutable` array, and so, each time we poll the API, the new array generated is not equal to the previous in-memory array regardless of its contents.

One way to sidestep seamless is to use `JSON.stringify()`, and compare the deep cloned arrays.

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js [hunk 2]
```diff
@@ -639,27 +641,41 @@ class PlanRequestDetailList extends React.Component {
...
+                        downloadLogInProgressTaskIds &&
+                        downloadLogInProgressTaskIds.find(element => element === task.id) &&
+                        !task.options.prePlaybookComplete &&
+                        !task.options.postPlaybookComplete
+                      }
+                    >
+                      {task.options.prePlaybookComplete && (
+                        <MenuItem
+                          eventKey="preMigration"
+                          disabled={downloadLogInProgressTaskIds && downloadLogInProgressTaskIds.indexOf(task.id) > -1}
```
[the remark this answers is not in the document]
Comment (AparnaKarve) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: The dropdown button is disabled only if 
```js
disabled={
  downloadLogInProgressTaskIds &&
  downloadLogInProgressTaskIds.find(element => element === task.id) &&
  !task.options.prePlaybookComplete &&
  !task.options.postPlaybookComplete
 }
```

So if `task.options.prePlaybookComplete` or `task.options.postPlaybookComplete` exists, the dropdown button would need to be clickable (right?), and then we have to disable the individual menu items.

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js (hunk 1 above)
Comment (AparnaKarve) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: `componentDidUpdate` does get called each time, and that is OK.

I was just making sure that the notification toasts for VM Migration completed/failed don't appear each time I try to click on the download dropdown or sort the list (things that cause the component to update)

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (michaelkro) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: Ahh ok.  So then we would allow downloading the migration log simultaneously with, say the pre-playbook log.

Right, ok, that makes sense.  Sorry, this is challenging to review without a good way to test these particular scenarios

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js (hunk 1 above)
Comment (michaelkro) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: ok good :)

I realized after I commented that my "fix" is particularly brittle b/c it relies on the order of the array elements

Comment (AparnaKarve) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: The best way to see the toast notification issue that I am referring to above is -
- Work with the `master` branch
- Try and download a log

--> you will see that the toast notifications are getting triggered, when they shouldn't

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (AparnaKarve) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: I tested it locally with some trickery -- so agree that it is challenging to review unless you test it.

File: app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js (hunk 1 above)
Comment (AparnaKarve) [reply app/javascript/react/screens/App/Plan/components/PlanRequestDetailList/PlanRequestDetailList.js]: As we discussed, let's address this issue separately.

I have removed the commit from the PR.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 7d78e6d95f04c23aa295e5afbc48fd1ccd8b173e
Author: Michael Ro <mikerodev@gmail.com>
Date:   Fri Sep 28 16:38:41 2018 -0400

    Merge pull request #670 from AparnaKarve/fix_download_log_related_alignment
    
    [#653] Fixes misalignment issues in the Plan detail list when download log is in progress
    
    (cherry picked from commit 616cfbbce184180aad67d2c2c286b029f214e74f)
```
